### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by talantbekov123** [Prysya/git-and-bash#2]
Хорошая работа, нужно сделать не большие исправления, что бы была корректная валидация примеров ниже. В проекте ветка develop отстает от ветки master, так не должно быть. Ветка develop должна содержать все актуальные изменения и после должна мержится с master.

**Отлично**
- эфективное регулярное выражение
- оформленное readme.md (Похвально, очень понравилось что вы использовали картинку https://camo.githubusercontent.com/181aebbe4c9e5516310c6fb50e94c520a854fa5b/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56657273696f6e2d302e302e322d626c75652e737667)
- работа на github pages, все поля работают
- нет лишних файлов в репозитории, есть gitignore
- требования к веткам соблюдены

**Надо исправить**
- **develop должна быть актуальной веткой, develop должна не отставать от master. Сначала делаете пуш в develop только потом мержите с мастер.** Подробнее [git push в master плохо](https://ru.stackoverflow.com/questions/672926/%D0%A1%D0%BB%D0%B0%D1%82%D1%8C-git-push-%D0%B2-master-%D0%BF%D0%BB%D0%BE%D1%85%D0%BE). Еще можно почитать эту статью, 4 пункт [(Упс… Я коммитнул изменения в master)](https://habr.com/ru/company/flant/blog/419733/)
- `review.test@yandex.ru` - В почте может присутствовать точка
- `review@test.yandex.ru` - Под домен может сожержать точку
- `http://google.ru///1///2///3` - количество слешей в пути должно быть ограничено одним экземпляром для каждой части пути
- `http://ya.ru:00000` - Проверку проходит следующий некорректный адре сайта. (в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными). Подробнее про порты можно почитать [тут](https://buy.fineproxy.org/articles/chto-takoe-port-servera.html)
- `http://11.11.11.11:0000` - Проверку проходит следующий некорректный адре сайта. (в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными). Подробнее про порты можно почитать [тут](https://buy.fineproxy.org/articles/chto-takoe-port-servera.html)

**Comment by Prysya** [comment]
Исправил паттерны. Насколько большая разница мерджить через сайт или через консоль?

**Comment by talantbekov123** [comment]
Хорошая работа, все комментарии исправленны! Похвально! Принимаю.


**Насколько большая разница мерджить через сайт или через консоль?**
Если вы имеете ввиду про pull request merge и merge через консоль, то это одно и тоже. Когда вы делаете слияние веток через сайт github, то сайт автоматически запускает скрипт который мержит ветки. Пример скрипта ниже.
```
git checkout <branch>
git merge --no-ff -m <message> <commit-hash>
```

Подробнее ответ на stackoverflow, ответ на англиском. Что либо не понятно, пишите.
https://stackoverflow.com/questions/57275242/github-pull-requests-vs-git-command-line-merging
